version: '3'

services:
  app:
    build: .
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://user:password@db/postgres

  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password

  # nginx:
  #   image: nginx
  #   ports:
  #     - "8000:80"  # Exposing nginx on port 8080
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/nginx.conf:ro  # Mounting custom nginx configuration
  #   depends_on:
  #     - app
